<a href="https://colab.research.google.com/github/AanyaChopra/ML_ASSIGNMENT-1/blob/main/ML_assignment1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
import numpy as np
# Creating arrays
arr = np.array([12,3,6,4,33,64,54,82,84,2,98,87])
ar = np.array([[12,3,6],[4,335,64]])

# eye (identity matrix)
eye_mat = np.eye(3)

# Attributes
print("Size:", ar.size)       # Total elements
print("Dimensions:", ar.ndim) # Number of dimensions
print("Shape:", ar.shape)     # Rows and columns

Size: 6
Dimensions: 2
Shape: (2, 3)


In [8]:
ar = np.array([[12,3,6],[4,335,64]])

# sum of whole array
print("Total sum:", ar.sum())

# add vertically (column-wise)
print("Axis 0 (Vertical):", ar.sum(axis=0))

# add horizontally (row-wise)
print("Axis 1 (Horizontal):", ar.sum(axis=1))

Total sum: 424
Axis 0 (Vertical): [ 16 338  70]
Axis 1 (Horizontal): [ 21 403]


In [11]:
# Reshaping (View)
arr = np.array([12, 3, 6, 4, 33, 64, 54, 82, 84, 2, 98, 87])
k = arr.reshape(3, 4)
arr[0] = 100
print("Original array after view change:", arr)
print("Reshaped view k:\n", k)  # Change reflects in original array

# Reshape with -1
ar = np.array([[12, 3, 6], [4, 335, 64]])
print("\nReshape with -1:\n", ar.reshape(-1, 3))

# 3D Reshape (FIXED: 2*1*3 = 6 elements)
print("\n3D Reshape:\n", ar.reshape(2, 1, 3))

Original array after view change: [100   3   6   4  33  64  54  82  84   2  98  87]
Reshaped view k:
 [[100   3   6   4]
 [ 33  64  54  82]
 [ 84   2  98  87]]

Reshape with -1:
 [[ 12   3   6]
 [  4 335  64]]

3D Reshape:
 [[[ 12   3   6]]

 [[  4 335  64]]]


In [12]:
# Make a copy and then change
arr = np.array([12,3,6,4,33,64,54,82,84,2,98,87])
k = arr.reshape(3,4).copy()
arr[0] = 100 # This won't affect k now
print("Original:", arr)
print("Copy k:", k)

# Ravel
ar = np.array([[12,3,6,3,56,78],[4,335,64,65,78,97]])
demo = ar.ravel()
demo[0] = 100
print("Raveled array:", demo)

Original: [100   3   6   4  33  64  54  82  84   2  98  87]
Copy k: [[12  3  6  4]
 [33 64 54 82]
 [84  2 98 87]]
Raveled array: [100   3   6   3  56  78   4 335  64  65  78  97]


In [13]:
# Broadcasting
d = np.array([100,23,45,67,89,98,87,65,43,32,56,78])
print("Broadcasting d*3:", d*3) # 3 will be multiplied to each element

# normal list
n = [5,6,7]
print("List n*3:", n*3) # will repeat the given list 3 times

# Masking
mask = (d > 80)
print("Mask:", mask)          # Prints True/False values
print("d[mask]:", d[mask])    # Prints true values
print("d[~mask]:", d[~mask])  # Approximation symbol prints false values

# Compound Masking
a = (d > 70) & (d < 90)
print("Compound mask d[a]:", d[a])

Broadcasting d*3: [300  69 135 201 267 294 261 195 129  96 168 234]
List n*3: [5, 6, 7, 5, 6, 7, 5, 6, 7]
Mask: [ True False False False  True  True  True False False False False False]
d[mask]: [100  89  98  87]
d[~mask]: [23 45 67 65 43 32 56 78]
Compound mask d[a]: [89 87 78]
